/*  =========================================================================
    cucumber-c - generated layer of public API

    Copyright (c) the Contributors as noted in the AUTHORS file. This
    file is part of cucumber-c.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef CUC_LIBRARY_H_INCLUDED
#define CUC_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#if defined (HAVE_GHERKIN)
#include <compiler.h>
#endif
#if defined (HAVE_MATH)
#include <math.h>
#endif
#if defined (HAVE_CJSON)
#include <cjson/cJSON.h>
#endif

//  CUC version macros for compile-time API detection
#define CUC_VERSION_MAJOR 0
#define CUC_VERSION_MINOR 1
#define CUC_VERSION_PATCH 0

#define CUC_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define CUC_VERSION \
    CUC_MAKE_VERSION(CUC_VERSION_MAJOR, CUC_VERSION_MINOR, CUC_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined CUC_STATIC
#       define CUC_EXPORT
#   elif defined CUC_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define CUC_EXPORT __declspec(dllexport)
#       else
#           define CUC_EXPORT
#       endif
#   elif defined CUC_EXPORTS
#       define CUC_EXPORT __declspec(dllexport)
#   else
#       define CUC_EXPORT __declspec(dllimport)
#   endif
#   define CUC_PRIVATE
#elif defined (__CYGWIN__)
#   define CUC_EXPORT
#   define CUC_PRIVATE
#else
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define CUC_PRIVATE __attribute__ ((visibility ("hidden")))
#       define CUC_EXPORT __attribute__ ((visibility ("default")))
#   else
#       define CUC_PRIVATE
#       define CUC_EXPORT
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  CUC_BUILD_DRAFT_API
#define CUC_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef CUC_BUILD_DRAFT_API
typedef struct _cuc_gherkin_doc_t cuc_gherkin_doc_t;
#define CUC_GHERKIN_DOC_T_DEFINED
typedef struct _cuc_pickle_t cuc_pickle_t;
#define CUC_PICKLE_T_DEFINED
typedef struct _cucumber_t cucumber_t;
#define CUCUMBER_T_DEFINED
typedef struct _cucumber_step_def_t cucumber_step_def_t;
#define CUCUMBER_STEP_DEF_T_DEFINED
#endif // CUC_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef CUC_BUILD_DRAFT_API
#include "cuc_gherkin_doc.h"
#include "cuc_pickle.h"
#include "cucumber.h"
#include "cucumber_step_def.h"
#endif // CUC_BUILD_DRAFT_API

#ifdef CUC_BUILD_DRAFT_API

#ifdef __cplusplus
extern "C" {
#endif

//  Self test for private classes
CUC_EXPORT void
    cuc_private_selftest (bool verbose, const char *subtest);

#ifdef __cplusplus
}
#endif
#endif // CUC_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
