/*  =========================================================================
    cucumber-c - generated layer of public API

    Copyright (c) the Contributors as noted in the AUTHORS file. This
    file is part of cucumber-c.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef CUCUMBER_LIBRARY_H_INCLUDED
#define CUCUMBER_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <compiler.h>
#include <cjson/cJSON.h>

//  CUCUMBER version macros for compile-time API detection
#define CUCUMBER_VERSION_MAJOR 0
#define CUCUMBER_VERSION_MINOR 1
#define CUCUMBER_VERSION_PATCH 0

#define CUCUMBER_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define CUCUMBER_VERSION \
    CUCUMBER_MAKE_VERSION(CUCUMBER_VERSION_MAJOR, CUCUMBER_VERSION_MINOR, CUCUMBER_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined CUCUMBER_STATIC
#       define CUCUMBER_EXPORT
#   elif defined CUCUMBER_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define CUCUMBER_EXPORT __declspec(dllexport)
#       else
#           define CUCUMBER_EXPORT
#       endif
#   elif defined CUCUMBER_EXPORTS
#       define CUCUMBER_EXPORT __declspec(dllexport)
#   else
#       define CUCUMBER_EXPORT __declspec(dllimport)
#   endif
#   define CUCUMBER_PRIVATE
#elif defined (__CYGWIN__)
#   define CUCUMBER_EXPORT
#   define CUCUMBER_PRIVATE
#else
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define CUCUMBER_PRIVATE __attribute__ ((visibility ("hidden")))
#       define CUCUMBER_EXPORT __attribute__ ((visibility ("default")))
#   else
#       define CUCUMBER_PRIVATE
#       define CUCUMBER_EXPORT
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  CUCUMBER_BUILD_DRAFT_API
#define CUCUMBER_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef CUCUMBER_BUILD_DRAFT_API
typedef struct _cucumber_feature_runner_t cucumber_feature_runner_t;
#define CUCUMBER_FEATURE_RUNNER_T_DEFINED
typedef struct _cuc_gherkin_doc_t cuc_gherkin_doc_t;
#define CUC_GHERKIN_DOC_T_DEFINED
typedef struct _cuc_pickle_t cuc_pickle_t;
#define CUC_PICKLE_T_DEFINED
typedef struct _cucumber_t cucumber_t;
#define CUCUMBER_T_DEFINED
typedef struct _cucumber_asserts_t cucumber_asserts_t;
#define CUCUMBER_ASSERTS_T_DEFINED
typedef struct _cucumber_step_def_t cucumber_step_def_t;
#define CUCUMBER_STEP_DEF_T_DEFINED
typedef struct _cucumber_steps_args_t cucumber_steps_args_t;
#define CUCUMBER_STEPS_ARGS_T_DEFINED
typedef struct _cucumber_steps_t cucumber_steps_t;
#define CUCUMBER_STEPS_T_DEFINED
#endif // CUCUMBER_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef CUCUMBER_BUILD_DRAFT_API
#include "cucumber_feature_runner.h"
#include "cuc_gherkin_doc.h"
#include "cuc_pickle.h"
#include "cucumber.h"
#include "cucumber_asserts.h"
#include "cucumber_step_def.h"
#include "cucumber_steps_args.h"
#include "cucumber_steps.h"
#endif // CUCUMBER_BUILD_DRAFT_API

#ifdef CUCUMBER_BUILD_DRAFT_API

#ifdef __cplusplus
extern "C" {
#endif

//  Self test for private classes
CUCUMBER_EXPORT void
    cucumber_private_selftest (bool verbose, const char *subtest);

#ifdef __cplusplus
}
#endif
#endif // CUCUMBER_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
